from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, Optional

from Utils.ToolBox.io_tools import read_json
from Utils.ToolBox.llm_clients.session_router import SessionRouter


def build_readme(
    cfg,
    doc_artifacts: Dict[str, Any],
    router: Optional[SessionRouter] = None,
    use_llm: bool = False,
) -> str:
    """
    Generate a curated README.md using artifacts.
    
    Args:
        cfg: PipelineConfig
        doc_artifacts: Doc artifacts dict from generate_doc_artifacts
        router: Optional SessionRouter for LLM calls
        use_llm: If True, use LLM to generate Problem/Goals/Summary sections
    
    Returns:
        README content as string
    """
    project_key = cfg.project_key
    
    # Load analyzer artifacts
    try:
        from Utils.ToolBox.artifact_loader import load_project_artifacts
        artifacts = load_project_artifacts(cfg.project_artifacts_dir)
        components = artifacts.get("components", {})
        deps = artifacts.get("deps", {})
    except Exception:
        components = {}
        deps = {}
    
    # Build README sections
    sections = []
    
    # Header
    sections.append(f"# {project_key}\n")
    
    # Overview (from LLM or default)
    if use_llm and router:
        overview = _generate_overview_with_llm(cfg, doc_artifacts, router)
        sections.append(f"{overview}\n")
    else:
        sections.append(f"Documentation for the {project_key} project.\n")
    
    # Project Structure
    sections.append("## Project Structure\n")
    modules = doc_artifacts.get("modules", [])
    if modules:
        sections.append(f"This project contains {len(modules)} modules:\n")
        for mod in modules[:10]:  # Limit to first 10 modules
            module_name = mod.get("module_name", "")
            module_path = mod.get("module_path", "")
            doc = mod.get("docstring", "").split("\n")[0]  # First line only
            if doc:
                sections.append(f"- **{module_name}** (`{module_path}`): {doc}\n")
            else:
                sections.append(f"- **{module_name}** (`{module_path}`)\n")
        if len(modules) > 10:
            sections.append(f"\n... and {len(modules) - 10} more modules.\n")
    
    # Components (if available)
    if components and components.get("components"):
        sections.append("\n## Components\n")
        for comp in components["components"][:5]:  # Limit to first 5
            comp_name = comp.get("name", "Unknown")
            comp_modules = comp.get("modules", [])
            sections.append(f"- **{comp_name}**: {len(comp_modules)} modules\n")
    
    # Dependencies (if available)
    if deps and deps.get("internal_dependencies"):
        sections.append("\n## Key Dependencies\n")
        internal_deps = deps["internal_dependencies"][:10]  # First 10
        for dep in internal_deps:
            source = dep.get("source", "")
            target = dep.get("target", "")
            sections.append(f"- `{source}` → `{target}`\n")
    
    # Quick Start
    sections.append("\n## Quick Start\n")
    sections.append("```python\n")
    sections.append(f"# Add your quick start example here\n")
    sections.append("```\n")
    
    # Documentation
    sections.append("\n## Documentation\n")
    sections.append(f"Full API documentation is available in the `Artifacts/{project_key}/docs/` directory.\n")
    
    # Generated by
    sections.append("\n---\n")
    sections.append("*This README was generated by the Multi-Agent Hierarchical Documentation system.*\n")
    
    return "".join(sections)


def _generate_overview_with_llm(cfg, doc_artifacts: Dict[str, Any], router: SessionRouter) -> str:
    """Generate project overview using LLM."""
    try:
        client = router.get_client("readme")
        
        # Build context from modules
        modules = doc_artifacts.get("modules", [])
        module_summaries = []
        for mod in modules[:5]:  # Use first 5 modules for context
            name = mod.get("module_name", "")
            doc = mod.get("docstring", "").split("\n")[0]
            if doc:
                module_summaries.append(f"- {name}: {doc}")
        
        context = "\n".join(module_summaries)
        
        prompt = f"""You are writing a README overview for a Python project called "{cfg.project_key}".

Based on these module descriptions:
{context}

Write a concise 2-3 paragraph overview describing:
1. What this project does (problem it solves)
2. Key features or capabilities
3. Who might use it

Keep it professional and to the point. Do not include headers or markdown formatting."""
        
        readme_params = cfg.llm_params_by_role.get("readme", cfg.llm_params)
        overview = client.generate(prompt, readme_params)
        
        router.release_role("readme")
        return overview.strip()
    except Exception as e:
        if cfg.debug:
            print(f"[README] LLM generation failed: {e}, using default")
        return f"Documentation for the {cfg.project_key} project."
